use crate::helpers::{has_default, is_auto_field};
use quiver_error::QuiverError;
use quiver_schema::Schema;
use quiver_schema::ast::*;

/// Generates TypeScript client types from a Quiver schema.
///
/// For each model, generates:
/// - Model interface (column fields only, no relations)
/// - CreateInput (excludes @id @autoincrement fields)
/// - UpdateInput (all non-auto fields optional)
/// - WhereUniqueInput (@id and @unique fields only)
/// - Field constants object
///
/// For each enum, generates a TypeScript string enum.
pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    pub fn generate(schema: &Schema) -> Result<String, QuiverError> {
        let mut out = String::new();

        out.push_str("// Generated by quiver-codegen. Do not edit.\n\n");

        for e in &schema.enums {
            gen_enum(&mut out, e);
        }

        for m in &schema.models {
            gen_model_interface(&mut out, m);
            gen_create_input(&mut out, m);
            gen_update_input(&mut out, m);
            gen_where_unique_input(&mut out, m);
            gen_field_constants(&mut out, m);
        }

        Ok(out)
    }
}

fn gen_enum(out: &mut String, e: &EnumDef) {
    out.push_str(&format!("export enum {} {{\n", e.name));
    for v in &e.values {
        out.push_str(&format!("  {} = \"{}\",\n", v.name, v.name));
    }
    out.push_str("}\n\n");
}

fn gen_model_interface(out: &mut String, m: &ModelDef) {
    out.push_str(&format!("export interface {} {{\n", m.name));
    for f in &m.fields {
        let ts_type = base_type_to_ts(&f.type_expr);
        if f.type_expr.nullable {
            out.push_str(&format!("  {}: {} | null;\n", f.name, ts_type));
        } else {
            out.push_str(&format!("  {}: {};\n", f.name, ts_type));
        }
    }
    out.push_str("}\n\n");
}

fn gen_create_input(out: &mut String, m: &ModelDef) {
    out.push_str(&format!("export interface {}CreateInput {{\n", m.name));
    for f in &m.fields {
        if is_auto_field(f) {
            continue;
        }
        let ts_type = base_type_to_ts(&f.type_expr);
        if f.type_expr.nullable || has_default(f) {
            out.push_str(&format!("  {}?: {} | null;\n", f.name, ts_type));
        } else {
            out.push_str(&format!("  {}: {};\n", f.name, ts_type));
        }
    }
    out.push_str("}\n\n");
}

fn gen_update_input(out: &mut String, m: &ModelDef) {
    out.push_str(&format!("export interface {}UpdateInput {{\n", m.name));
    for f in &m.fields {
        if is_auto_field(f) {
            continue;
        }
        let ts_type = base_type_to_ts(&f.type_expr);
        if f.type_expr.nullable {
            out.push_str(&format!("  {}?: {} | null;\n", f.name, ts_type));
        } else {
            out.push_str(&format!("  {}?: {};\n", f.name, ts_type));
        }
    }
    out.push_str("}\n\n");
}

fn gen_where_unique_input(out: &mut String, m: &ModelDef) {
    out.push_str(&format!("export interface {}WhereUniqueInput {{\n", m.name));
    for f in &m.fields {
        if !is_id_field(f) && !is_unique_field(f) {
            continue;
        }
        let ts_type = base_type_to_ts(&f.type_expr);
        if f.type_expr.nullable {
            out.push_str(&format!("  {}?: {} | null;\n", f.name, ts_type));
        } else {
            out.push_str(&format!("  {}: {};\n", f.name, ts_type));
        }
    }
    out.push_str("}\n\n");
}

fn gen_field_constants(out: &mut String, m: &ModelDef) {
    out.push_str(&format!("export const {}Fields = {{\n", m.name));
    for f in &m.fields {
        out.push_str(&format!("  {}: \"{}\",\n", f.name, f.name));
    }
    out.push_str("} as const;\n\n");
}

fn base_type_to_ts(type_expr: &TypeExpr) -> String {
    match &type_expr.base {
        // Integers (fit in JS number)
        BaseType::Int8
        | BaseType::Int16
        | BaseType::Int32
        | BaseType::UInt8
        | BaseType::UInt16
        | BaseType::UInt32 => "number".into(),

        // 64-bit integers -> bigint
        BaseType::Int64 | BaseType::UInt64 => "bigint".into(),

        // Floats
        BaseType::Float16 | BaseType::Float32 | BaseType::Float64 => "number".into(),

        // Decimals -> string for precision preservation
        BaseType::Decimal128 { .. } | BaseType::Decimal256 { .. } => "string".into(),

        // Strings
        BaseType::Utf8 | BaseType::LargeUtf8 => "string".into(),

        // Binary
        BaseType::Binary | BaseType::LargeBinary | BaseType::FixedSizeBinary { .. } => {
            "Uint8Array".into()
        }

        // Boolean
        BaseType::Boolean => "boolean".into(),

        // Temporal -> ISO string representations
        BaseType::Date32 | BaseType::Date64 => "string".into(),
        BaseType::Time32 { .. } | BaseType::Time64 { .. } => "string".into(),
        BaseType::Timestamp { .. } => "string".into(),

        // Nested types
        BaseType::List(inner) | BaseType::LargeList(inner) => {
            let inner_ts = base_type_to_ts(inner);
            if inner.nullable {
                format!("({inner_ts} | null)[]")
            } else {
                format!("{inner_ts}[]")
            }
        }

        BaseType::Map { key, value } => {
            let key_ts = base_type_to_ts(key);
            let value_ts = base_type_to_ts(value);
            format!("Map<{key_ts}, {value_ts}>")
        }

        BaseType::Struct(fields) => {
            let mut parts = Vec::new();
            for sf in fields {
                let ft = base_type_to_ts(&sf.type_expr);
                if sf.type_expr.nullable {
                    parts.push(format!("{}: {} | null", sf.name, ft));
                } else {
                    parts.push(format!("{}: {}", sf.name, ft));
                }
            }
            format!("{{ {} }}", parts.join("; "))
        }

        // Named reference: enum or relation model -- both use the type name directly
        BaseType::Named(name) => name.clone(),
    }
}

fn is_id_field(f: &FieldDef) -> bool {
    f.attributes.iter().any(|a| matches!(a, FieldAttribute::Id))
}

fn is_unique_field(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Unique))
}

#[cfg(test)]
mod tests {
    use super::*;
    use quiver_schema::parse;

    #[test]
    fn simple_model_generates_correct_interface() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8?
                age   Int32
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        assert!(code.contains("export interface User {"));
        assert!(code.contains("  id: number;"));
        assert!(code.contains("  email: string;"));
        assert!(code.contains("  name: string | null;"));
        assert!(code.contains("  age: number;"));
    }

    #[test]
    fn enum_generates_correct_ts_enum() {
        let schema = parse(
            r#"
            enum Role {
                User
                Admin
                Moderator
            }
            model Account {
                id   Int32 PRIMARY KEY
                role Role
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        assert!(code.contains("export enum Role {"));
        assert!(code.contains("  User = \"User\","));
        assert!(code.contains("  Admin = \"Admin\","));
        assert!(code.contains("  Moderator = \"Moderator\","));
        // Enum field in model should reference the enum type
        assert!(code.contains("  role: Role;"));
    }

    #[test]
    fn create_input_excludes_auto_fields() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8?
                score Int32  DEFAULT 0
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        assert!(code.contains("export interface UserCreateInput {"));
        // id should be excluded (has @id @autoincrement)
        let create_section = extract_block(&code, "export interface UserCreateInput {");
        assert!(!create_section.contains("id:"));
        assert!(!create_section.contains("id?:"));
        // email is required
        assert!(create_section.contains("  email: string;"));
        // name is nullable -> optional
        assert!(create_section.contains("  name?: string | null;"));
        // score has default -> optional
        assert!(create_section.contains("  score?: number | null;"));
    }

    #[test]
    fn update_input_has_all_optional_fields() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8?
                age   Int32
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        assert!(code.contains("export interface UserUpdateInput {"));
        let update_section = extract_block(&code, "export interface UserUpdateInput {");
        // id excluded (auto field)
        assert!(!update_section.contains("id"));
        // All fields optional
        assert!(update_section.contains("  email?: string;"));
        assert!(update_section.contains("  name?: string | null;"));
        assert!(update_section.contains("  age?: number;"));
    }

    #[test]
    fn nullable_fields_use_null_union() {
        let schema = parse(
            r#"
            model Post {
                id      Int32  PRIMARY KEY AUTOINCREMENT
                title   Utf8
                content Utf8?
                rating  Float64?
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        // Model interface
        let model_section = extract_block(&code, "export interface Post {");
        assert!(model_section.contains("  title: string;"));
        assert!(model_section.contains("  content: string | null;"));
        assert!(model_section.contains("  rating: number | null;"));
    }

    #[test]
    fn where_unique_input_only_id_and_unique_fields() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8
                code  Utf8   UNIQUE
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        let where_section = extract_block(&code, "export interface UserWhereUniqueInput {");
        assert!(where_section.contains("  id: number;"));
        assert!(where_section.contains("  email: string;"));
        assert!(where_section.contains("  code: string;"));
        // name is not @id or @unique
        assert!(!where_section.contains("name"));
    }

    #[test]
    fn field_constants_generated() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8?
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        assert!(code.contains("export const UserFields = {"));
        assert!(code.contains("  id: \"id\","));
        assert!(code.contains("  email: \"email\","));
        assert!(code.contains("  name: \"name\","));
        assert!(code.contains("} as const;"));
    }

    #[test]
    fn relation_fields_excluded_from_interface() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
            }
            model Post {
                id       Int32 PRIMARY KEY AUTOINCREMENT
                authorId Int32
                FOREIGN KEY (authorId) REFERENCES User (id)
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        let user_section = extract_block(&code, "export interface User {");
        assert!(user_section.contains("  id: number;"));
        assert!(!user_section.contains("posts"));

        let post_section = extract_block(&code, "export interface Post {");
        assert!(post_section.contains("  id: number;"));
        assert!(post_section.contains("  authorId: number;"));
        // "author" as a standalone field should not appear (only authorId)
        assert!(!post_section.contains("  author:"));
        assert!(!post_section.contains("  author?:"));
    }

    #[test]
    fn bigint_and_binary_type_mapping() {
        let schema = parse(
            r#"
            model Record {
                id    Int32  PRIMARY KEY
                big   Int64
                ubig  UInt64
                data  Binary
            }
        "#,
        )
        .unwrap();
        let code = TypeScriptGenerator::generate(&schema).unwrap();

        let section = extract_block(&code, "export interface Record {");
        assert!(section.contains("  big: bigint;"));
        assert!(section.contains("  ubig: bigint;"));
        assert!(section.contains("  data: Uint8Array;"));
    }

    /// Helper: extract a `{ ... }` block starting from a marker line.
    fn extract_block(code: &str, marker: &str) -> String {
        let start = code.find(marker).expect("marker not found in code");
        let rest = &code[start..];
        // Find matching closing brace
        let mut depth = 0;
        let mut end = 0;
        for (i, ch) in rest.char_indices() {
            if ch == '{' {
                depth += 1;
            } else if ch == '}' {
                depth -= 1;
                if depth == 0 {
                    end = i + 1;
                    break;
                }
            }
        }
        rest[..end].to_string()
    }
}
