use quiver_error::QuiverError;
use quiver_schema::Schema;
use quiver_schema::ast::*;

/// Generates native Rust structs with serde derives from a Quiver schema.
///
/// Unlike the FBS/Proto backends, this generates idiomatic Rust types directly
/// without an intermediate schema format.
pub struct RustSerdeGenerator;

impl RustSerdeGenerator {
    pub fn generate(schema: &Schema) -> Result<String, QuiverError> {
        let mut out = String::new();

        out.push_str("// Generated by quiver-codegen. Do not edit.\n\n");
        out.push_str("use serde::{Serialize, Deserialize};\n");
        out.push_str("use quiver_driver_core::{Row, RowError};\n\n");

        for e in &schema.enums {
            gen_enum(&mut out, e);
        }

        for m in &schema.models {
            gen_struct(&mut out, m, schema);
            gen_try_from_row(&mut out, m, schema);
            gen_create_input(&mut out, m, schema);
            gen_update_input(&mut out, m, schema);
        }

        Ok(out)
    }
}

fn gen_enum(out: &mut String, e: &EnumDef) {
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub enum {} {{\n", e.name));
    for v in &e.values {
        out.push_str(&format!("    {},\n", v.name));
    }
    out.push_str("}\n\n");

    // Generate Display impl (variant name as string)
    out.push_str(&format!("impl std::fmt::Display for {} {{\n", e.name));
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        match self {\n");
    for v in &e.values {
        out.push_str(&format!(
            "            {}::{} => write!(f, \"{}\"),\n",
            e.name, v.name, v.name
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Generate FromStr impl (for Row deserialization: text -> enum)
    out.push_str(&format!("impl std::str::FromStr for {} {{\n", e.name));
    out.push_str("    type Err = RowError;\n\n");
    out.push_str("    fn from_str(s: &str) -> Result<Self, Self::Err> {\n");
    out.push_str("        match s {\n");
    for v in &e.values {
        out.push_str(&format!(
            "            \"{}\" => Ok({}::{}),\n",
            v.name, e.name, v.name
        ));
    }
    out.push_str(&format!(
        "            _ => Err(RowError {{ message: format!(\"unknown {} variant: '{{}}'\", s) }}),\n",
        e.name
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn gen_struct(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");

    // Add serde rename_all if @@map is present (indicates non-Rust naming)
    if get_map_name(&m.attributes).is_some() {
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
    }

    out.push_str(&format!("pub struct {} {{\n", m.name));
    for f in &m.fields {
        let rust_type = type_to_rust(&f.type_expr, schema);
        let col_rename = get_field_map_name(f);
        if let Some(rename) = col_rename {
            out.push_str(&format!("    #[serde(rename = \"{}\")]\n", rename));
        }
        out.push_str(&format!("    pub {}: {},\n", to_snake(&f.name), rust_type));
    }
    out.push_str("}\n\n");
}

/// Generate `TryFrom<&Row>` implementation for a model struct.
///
/// Uses the typed `Row` accessor methods (`.text()`, `.int32()`, `.boolean()`, etc.)
/// added in quiver-driver-core. The column name used for lookup is the original
/// schema field name (e.g., "parentId"), NOT the snake_case Rust field name.
/// If a field has a `MAP` attribute, the mapped name is used instead.
fn gen_try_from_row(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str(&format!("impl TryFrom<&Row> for {} {{\n", m.name));
    out.push_str("    type Error = RowError;\n\n");
    out.push_str("    fn try_from(row: &Row) -> Result<Self, Self::Error> {\n");
    out.push_str("        Ok(Self {\n");

    for f in &m.fields {
        // The column name in the database: use @map rename if present, otherwise
        // the original schema field name (which is typically camelCase).
        let col_name = get_field_map_name(f).unwrap_or(&f.name);
        let rust_field = to_snake(&f.name);

        // Enum fields need parsing: text -> enum via FromStr
        if let BaseType::Named(name) = &f.type_expr.base {
            if schema.enums.iter().any(|e| e.name == *name) {
                if f.type_expr.nullable {
                    out.push_str(&format!(
                        "            {}: row.optional_text(\"{}\")?.map(|s| s.parse::<{}>()).transpose()?,\n",
                        rust_field, col_name, name
                    ));
                } else {
                    out.push_str(&format!(
                        "            {}: row.text(\"{}\")?.parse::<{}>()?,\n",
                        rust_field, col_name, name
                    ));
                }
                continue;
            }
        }

        let accessor = row_accessor_for_type(&f.type_expr, schema);
        out.push_str(&format!(
            "            {}: row.{}(\"{}\")?,\n",
            rust_field, accessor, col_name
        ));
    }

    out.push_str("        })\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

/// Return the Row accessor method name for a given schema type.
///
/// Maps schema types to the typed Row methods:
///   - Utf8/LargeUtf8/temporal/decimal -> text() / optional_text()
///   - Int8..Int32, UInt8..UInt16, Named(FK) -> int32() / optional_int32()
///   - Int64, UInt32..UInt64 -> int64() / optional_int64()
///   - Float* -> float64() / optional_float64()
///   - Boolean -> boolean() / optional_boolean()
///   - Binary* -> blob() / optional_blob()
///   - Named(enum) -> text() (enums are stored as text in the DB)
fn row_accessor_for_type(type_expr: &TypeExpr, schema: &Schema) -> &'static str {
    let optional = type_expr.nullable;
    match &type_expr.base {
        // String types and temporal (all stored as text in SQLite)
        BaseType::Utf8
        | BaseType::LargeUtf8
        | BaseType::Date32
        | BaseType::Date64
        | BaseType::Time32 { .. }
        | BaseType::Time64 { .. }
        | BaseType::Timestamp { .. }
        | BaseType::Decimal128 { .. }
        | BaseType::Decimal256 { .. } => {
            if optional {
                "optional_text"
            } else {
                "text"
            }
        }

        // Small integers -> i32
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 | BaseType::UInt8 | BaseType::UInt16 => {
            if optional {
                "optional_int32"
            } else {
                "int32"
            }
        }

        // Large integers -> i64
        BaseType::Int64 | BaseType::UInt32 | BaseType::UInt64 => {
            if optional {
                "optional_int64"
            } else {
                "int64"
            }
        }

        // Floats
        BaseType::Float16 | BaseType::Float32 | BaseType::Float64 => {
            if optional {
                "optional_float64"
            } else {
                "float64"
            }
        }

        // Boolean
        BaseType::Boolean => {
            if optional {
                "optional_boolean"
            } else {
                "boolean"
            }
        }

        // Binary
        BaseType::Binary | BaseType::LargeBinary | BaseType::FixedSizeBinary { .. } => {
            if optional {
                "optional_blob"
            } else {
                "blob"
            }
        }

        // Named type: enum -> text, FK reference -> i32
        BaseType::Named(name) => {
            if schema.enums.iter().any(|e| e.name == *name) {
                // Enum stored as text
                if optional { "optional_text" } else { "text" }
            } else {
                // FK reference -> integer
                if optional { "optional_int32" } else { "int32" }
            }
        }

        // Collections/struct stored as JSON text
        BaseType::List(_) | BaseType::LargeList(_) | BaseType::Map { .. } | BaseType::Struct(_) => {
            if optional {
                "optional_text"
            } else {
                "text"
            }
        }
    }
}

fn gen_create_input(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {}CreateInput {{\n", m.name));
    for f in &m.fields {
        if is_auto_field(f) {
            continue;
        }
        let base_type = type_to_rust(&f.type_expr, schema);
        // Fields with defaults or nullable become Option in create input
        if has_default(f) && !f.type_expr.nullable {
            out.push_str(&format!(
                "    pub {}: Option<{}>,\n",
                to_snake(&f.name),
                base_rust_type(&f.type_expr.base, schema)
            ));
        } else {
            out.push_str(&format!("    pub {}: {},\n", to_snake(&f.name), base_type));
        }
    }
    out.push_str("}\n\n");
}

fn gen_update_input(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {}UpdateInput {{\n", m.name));
    for f in &m.fields {
        if is_auto_field(f) {
            continue;
        }
        let base = base_rust_type(&f.type_expr.base, schema);
        // All fields optional in update
        out.push_str(&format!(
            "    pub {}: Option<{}>,\n",
            to_snake(&f.name),
            base
        ));
    }
    out.push_str("}\n\n");
}

fn type_to_rust(type_expr: &TypeExpr, schema: &Schema) -> String {
    let base = base_rust_type(&type_expr.base, schema);
    if type_expr.nullable {
        format!("Option<{}>", base)
    } else {
        base
    }
}

fn base_rust_type(base: &BaseType, schema: &Schema) -> String {
    match base {
        BaseType::Int8 => "i8".into(),
        BaseType::Int16 => "i16".into(),
        BaseType::Int32 => "i32".into(),
        BaseType::Int64 => "i64".into(),
        BaseType::UInt8 => "u8".into(),
        BaseType::UInt16 => "u16".into(),
        BaseType::UInt32 => "u32".into(),
        BaseType::UInt64 => "u64".into(),
        BaseType::Float16 => "f32".into(),
        BaseType::Float32 => "f32".into(),
        BaseType::Float64 => "f64".into(),
        BaseType::Decimal128 { .. } | BaseType::Decimal256 { .. } => "String".into(),
        BaseType::Utf8 | BaseType::LargeUtf8 => "String".into(),
        BaseType::Binary | BaseType::LargeBinary | BaseType::FixedSizeBinary { .. } => {
            "Vec<u8>".into()
        }
        BaseType::Boolean => "bool".into(),
        BaseType::Date32 | BaseType::Date64 => "String".into(),
        BaseType::Time32 { .. } | BaseType::Time64 { .. } => "String".into(),
        BaseType::Timestamp { .. } => "String".into(),
        BaseType::List(inner) | BaseType::LargeList(inner) => {
            format!("Vec<{}>", base_rust_type(&inner.base, schema))
        }
        BaseType::Map { key, value } => {
            format!(
                "std::collections::HashMap<{}, {}>",
                base_rust_type(&key.base, schema),
                base_rust_type(&value.base, schema)
            )
        }
        BaseType::Struct(_) => "serde_json::Value".into(),
        BaseType::Named(name) => {
            if schema.enums.iter().any(|e| e.name == *name) {
                name.clone()
            } else {
                // FK reference -- use the PK type (assume i32 for now)
                "i32".into()
            }
        }
    }
}

fn to_snake(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    result
}

fn is_auto_field(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Autoincrement | FieldAttribute::Id))
}

fn has_default(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Default(_)))
}

fn get_map_name(attrs: &[ModelAttribute]) -> Option<&str> {
    for attr in attrs {
        if let ModelAttribute::Map(name) = attr {
            return Some(name);
        }
    }
    None
}

fn get_field_map_name(f: &FieldDef) -> Option<&str> {
    for attr in &f.attributes {
        if let FieldAttribute::Map(name) = attr {
            return Some(name);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use quiver_schema::parse;

    #[test]
    fn generate_simple_struct() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8?
                age   Int16
                active Boolean DEFAULT true
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct User {"));
        assert!(code.contains("pub email: String,"));
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains("pub age: i16,"));
        assert!(code.contains("pub active: bool,"));
        assert!(code.contains("pub id: i32,"));
    }

    #[test]
    fn generate_try_from_row() {
        let schema = parse(
            r#"
            model User {
                id     Int32   PRIMARY KEY AUTOINCREMENT
                email  Utf8    UNIQUE
                name   Utf8?
                age    Int16
                active Boolean DEFAULT true
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        // TryFrom<&Row> impl generated
        assert!(code.contains("impl TryFrom<&Row> for User {"));
        assert!(code.contains("type Error = RowError;"));
        // Uses typed Row accessors with original column names
        assert!(code.contains("id: row.int32(\"id\")?,"));
        assert!(code.contains("email: row.text(\"email\")?,"));
        assert!(code.contains("name: row.optional_text(\"name\")?,"));
        assert!(code.contains("age: row.int32(\"age\")?,"));
        assert!(code.contains("active: row.boolean(\"active\")?,"));
    }

    #[test]
    fn generate_try_from_row_with_map_rename() {
        let schema = parse(
            r#"
            model UserProfile {
                id       Int32 PRIMARY KEY
                fullName Utf8  MAP "full_name"
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        // TryFrom uses the @map name for column lookup
        assert!(code.contains("full_name: row.text(\"full_name\")?,"));
    }

    #[test]
    fn generate_try_from_row_nullable_int() {
        let schema = parse(
            r#"
            model Issue {
                id           Int32  PRIMARY KEY AUTOINCREMENT
                parentId     Int32?
                componentId  Int32
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("parent_id: row.optional_int32(\"parentId\")?,"));
        assert!(code.contains("component_id: row.int32(\"componentId\")?,"));
    }

    #[test]
    fn generate_enum_with_display_and_from_str() {
        let schema = parse(
            r#"
            enum Role { User Admin Moderator }
            model Account {
                id   Int32 PRIMARY KEY
                role Role
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        // Enum definition
        assert!(code.contains("pub enum Role {"));
        assert!(code.contains("    User,"));
        // Display impl
        assert!(code.contains("impl std::fmt::Display for Role {"));
        // FromStr impl
        assert!(code.contains("impl std::str::FromStr for Role {"));
        assert!(code.contains("\"User\" => Ok(Role::User),"));
        assert!(code.contains("\"Admin\" => Ok(Role::Admin),"));
        // TryFrom<&Row> uses parse for enum fields
        assert!(code.contains("role: row.text(\"role\")?.parse::<Role>()?,"));
    }

    #[test]
    fn generate_enum_nullable_field() {
        let schema = parse(
            r#"
            enum Status { Active Inactive }
            model User {
                id     Int32   PRIMARY KEY
                status Status?
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        // Nullable enum uses optional_text + map + parse
        assert!(code.contains(
            "status: row.optional_text(\"status\")?.map(|s| s.parse::<Status>()).transpose()?,"
        ));
    }

    #[test]
    fn generate_imports_include_row() {
        let schema = parse(
            r#"
            model Item {
                id   Int32 PRIMARY KEY
                name Utf8
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("use quiver_driver_core::{Row, RowError};"));
    }

    #[test]
    fn generate_create_input_excludes_auto() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8
                name  Utf8?
                active Boolean DEFAULT true
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct UserCreateInput {"));
        let create_block = code.split("pub struct UserCreateInput").nth(1).unwrap();
        let create_block = create_block.split('}').next().unwrap();
        assert!(!create_block.contains("id:"));
        assert!(create_block.contains("pub email: String,"));
        assert!(create_block.contains("pub name: Option<String>,"));
        assert!(create_block.contains("pub active: Option<bool>,"));
    }

    #[test]
    fn generate_update_input_all_optional() {
        let schema = parse(
            r#"
            model User {
                id    Int32 PRIMARY KEY AUTOINCREMENT
                email Utf8
                score Int32
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct UserUpdateInput {"));
        let update_block = code.split("pub struct UserUpdateInput").nth(1).unwrap();
        let update_block = update_block.split('}').next().unwrap();
        assert!(update_block.contains("pub email: Option<String>,"));
        assert!(update_block.contains("pub score: Option<i32>,"));
        assert!(!update_block.contains("id:"));
    }

    #[test]
    fn generate_list_and_map_types() {
        let schema = parse(
            r#"
            model Doc {
                id    Int32 PRIMARY KEY
                tags  List<Utf8>
                meta  Map<Utf8, Int32>
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub tags: Vec<String>,"));
        assert!(code.contains("pub meta: std::collections::HashMap<String, i32>,"));
    }

    #[test]
    fn generate_temporal_types() {
        let schema = parse(
            r#"
            model Event {
                id      Int32 PRIMARY KEY
                created Timestamp(Microsecond, UTC)
                day     Date32
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub created: String,"));
        assert!(code.contains("pub day: String,"));
    }

    #[test]
    fn generate_field_rename() {
        let schema = parse(
            r#"
            model UserProfile {
                id       Int32 PRIMARY KEY
                fullName Utf8  MAP "full_name"
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("#[serde(rename = \"full_name\")]"));
        assert!(code.contains("pub full_name: String,"));
    }

    #[test]
    fn generate_relation_excluded() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY
            }
            model Post {
                id       Int32 PRIMARY KEY
                authorId Int32
                FOREIGN KEY (authorId) REFERENCES User (id)
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        let user_block = code.split("pub struct User {").nth(1).unwrap();
        let user_block = user_block.split('}').next().unwrap();
        assert!(!user_block.contains("posts"));

        let post_block = code.split("pub struct Post {").nth(1).unwrap();
        let post_block = post_block.split('}').next().unwrap();
        assert!(!post_block.contains("pub author:"));
        assert!(post_block.contains("pub author_id: i32,"));
    }

    #[test]
    fn derive_default_on_update_input() {
        let schema = parse(
            r#"
            model Item {
                id   Int32 PRIMARY KEY AUTOINCREMENT
                name Utf8
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("#[derive(Debug, Clone, Default, Serialize, Deserialize)]"));
    }
}
