use quiver_error::QuiverError;
use quiver_schema::Schema;
use quiver_schema::ast::*;

/// Generates a type-safe Rust client from a Quiver schema.
///
/// For each model, generates a module with:
/// - Field name constants (`&'static str`)
/// - Query entry points (`find_many()`, `create()`, etc.)
/// - Per-field filter constructors
/// - Relation definitions for eager loading
/// - Typed `CreateData`/`UpdateData` structs
pub struct RustClientGenerator;

impl RustClientGenerator {
    pub fn generate(schema: &Schema) -> Result<String, QuiverError> {
        let mut out = String::new();

        out.push_str("// Generated by quiver-codegen. Do not edit.\n\n");
        out.push_str("use quiver_driver_core::Value;\n");
        out.push_str("use quiver_query::{Query, BuiltQuery, Filter, Order};\n");
        out.push_str("use quiver_query::{FindManyBuilder, FindFirstBuilder, CreateBuilder};\n");
        out.push_str(
            "use quiver_query::{CreateManyBuilder, UpdateBuilder, DeleteBuilder, UpsertBuilder};\n",
        );
        out.push_str(
            "use quiver_query::{AggregateBuilder, RelationDef, RelationType, Include};\n\n",
        );

        for m in &schema.models {
            gen_model_module(&mut out, m, schema);
        }

        Ok(out)
    }
}

fn gen_model_module(out: &mut String, m: &ModelDef, schema: &Schema) {
    let mod_name = to_snake(&m.name);
    let table_name = get_table_name(m);

    out.push_str(&format!("pub mod {} {{\n", mod_name));
    out.push_str("    use super::*;\n\n");

    gen_field_constants(out, m);
    gen_query_entry_points(out, &table_name);
    gen_filter_helpers(out, m, schema);
    gen_order_helpers(out, m, schema);
    gen_relation_defs(out, m, schema);
    gen_create_data(out, m, schema);
    gen_update_data(out, m, schema);

    out.push_str("}\n\n");
}

fn gen_field_constants(out: &mut String, m: &ModelDef) {
    out.push_str("    pub mod fields {\n");
    for f in &m.fields {
        if is_relation_object(f) {
            continue;
        }
        let const_name = to_screaming_snake(&f.name);
        out.push_str(&format!(
            "        pub const {}: &str = \"{}\";\n",
            const_name, f.name
        ));
    }
    out.push_str("    }\n\n");
}

fn gen_query_entry_points(out: &mut String, table_name: &str) {
    // find_many
    out.push_str(&format!(
        "    pub fn find_many() -> FindManyBuilder {{\n        Query::table(\"{}\").find_many()\n    }}\n\n",
        table_name
    ));

    // find_first
    out.push_str(&format!(
        "    pub fn find_first() -> FindFirstBuilder {{\n        Query::table(\"{}\").find_first()\n    }}\n\n",
        table_name
    ));

    // create
    out.push_str(&format!(
        "    pub fn create() -> CreateBuilder {{\n        Query::table(\"{}\").create()\n    }}\n\n",
        table_name
    ));

    // create_many
    out.push_str(&format!(
        "    pub fn create_many() -> CreateManyBuilder {{\n        Query::table(\"{}\").create_many()\n    }}\n\n",
        table_name
    ));

    // update
    out.push_str(&format!(
        "    pub fn update() -> UpdateBuilder {{\n        Query::table(\"{}\").update()\n    }}\n\n",
        table_name
    ));

    // update_many
    out.push_str(&format!(
        "    pub fn update_many() -> UpdateBuilder {{\n        Query::table(\"{}\").update_many()\n    }}\n\n",
        table_name
    ));

    // delete
    out.push_str(&format!(
        "    pub fn delete() -> DeleteBuilder {{\n        Query::table(\"{}\").delete()\n    }}\n\n",
        table_name
    ));

    // delete_many
    out.push_str(&format!(
        "    pub fn delete_many() -> DeleteBuilder {{\n        Query::table(\"{}\").delete_many()\n    }}\n\n",
        table_name
    ));

    // aggregate
    out.push_str(&format!(
        "    pub fn aggregate() -> AggregateBuilder {{\n        Query::table(\"{}\").aggregate()\n    }}\n\n",
        table_name
    ));
}

fn gen_filter_helpers(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("    pub mod filter {\n");
    out.push_str("        use super::*;\n\n");

    for f in &m.fields {
        if is_relation_object(f) {
            continue;
        }

        let field_name = &f.name;
        let fn_prefix = to_snake(field_name);
        let filter_type = classify_filter_type(&f.type_expr, schema);

        // eq
        out.push_str(&format!(
            "        pub fn {}_eq(value: impl Into<Value>) -> Filter {{\n",
            fn_prefix
        ));
        out.push_str(&format!(
            "            Filter::eq(\"{}\", value)\n",
            field_name
        ));
        out.push_str("        }\n\n");

        // neq
        out.push_str(&format!(
            "        pub fn {}_neq(value: impl Into<Value>) -> Filter {{\n",
            fn_prefix
        ));
        out.push_str(&format!(
            "            Filter::neq(\"{}\", value)\n",
            field_name
        ));
        out.push_str("        }\n\n");

        // is_null (for nullable fields)
        if f.type_expr.nullable {
            out.push_str(&format!(
                "        pub fn {}_is_null() -> Filter {{\n",
                fn_prefix
            ));
            out.push_str(&format!(
                "            Filter::is_null(\"{}\")\n",
                field_name
            ));
            out.push_str("        }\n\n");

            out.push_str(&format!(
                "        pub fn {}_is_not_null() -> Filter {{\n",
                fn_prefix
            ));
            out.push_str(&format!(
                "            Filter::is_not_null(\"{}\")\n",
                field_name
            ));
            out.push_str("        }\n\n");
        }

        // in
        out.push_str(&format!(
            "        pub fn {}_in(values: Vec<Value>) -> Filter {{\n",
            fn_prefix
        ));
        out.push_str(&format!(
            "            Filter::is_in(\"{}\", values)\n",
            field_name
        ));
        out.push_str("        }\n\n");

        match filter_type {
            FilterType::Numeric => {
                for (suffix, method) in
                    &[("gt", "gt"), ("gte", "gte"), ("lt", "lt"), ("lte", "lte")]
                {
                    out.push_str(&format!(
                        "        pub fn {}_{suffix}(value: impl Into<Value>) -> Filter {{\n",
                        fn_prefix
                    ));
                    out.push_str(&format!(
                        "            Filter::{method}(\"{field_name}\", value)\n",
                    ));
                    out.push_str("        }\n\n");
                }

                // between
                out.push_str(&format!(
                    "        pub fn {}_between(low: impl Into<Value>, high: impl Into<Value>) -> Filter {{\n",
                    fn_prefix
                ));
                out.push_str(&format!(
                    "            Filter::between(\"{}\", low, high)\n",
                    field_name
                ));
                out.push_str("        }\n\n");
            }
            FilterType::String => {
                // like
                out.push_str(&format!(
                    "        pub fn {}_like(pattern: impl Into<Value>) -> Filter {{\n",
                    fn_prefix
                ));
                out.push_str(&format!(
                    "            Filter::like(\"{}\", pattern)\n",
                    field_name
                ));
                out.push_str("        }\n\n");

                // contains (convenience for %value%)
                out.push_str(&format!(
                    "        pub fn {}_contains(value: &str) -> Filter {{\n",
                    fn_prefix
                ));
                out.push_str(&format!(
                    "            Filter::like(\"{}\", format!(\"%{{}}%\", value))\n",
                    field_name
                ));
                out.push_str("        }\n\n");

                // starts_with
                out.push_str(&format!(
                    "        pub fn {}_starts_with(value: &str) -> Filter {{\n",
                    fn_prefix
                ));
                out.push_str(&format!(
                    "            Filter::like(\"{}\", format!(\"{{}}%\", value))\n",
                    field_name
                ));
                out.push_str("        }\n\n");

                // gt/gte/lt/lte for ordering comparisons
                for (suffix, method) in
                    &[("gt", "gt"), ("gte", "gte"), ("lt", "lt"), ("lte", "lte")]
                {
                    out.push_str(&format!(
                        "        pub fn {}_{suffix}(value: impl Into<Value>) -> Filter {{\n",
                        fn_prefix
                    ));
                    out.push_str(&format!(
                        "            Filter::{method}(\"{field_name}\", value)\n",
                    ));
                    out.push_str("        }\n\n");
                }
            }
            FilterType::Boolean => {
                // is_true / is_false
                out.push_str(&format!(
                    "        pub fn {}_is_true() -> Filter {{\n",
                    fn_prefix
                ));
                out.push_str(&format!(
                    "            Filter::eq(\"{}\", true)\n",
                    field_name
                ));
                out.push_str("        }\n\n");

                out.push_str(&format!(
                    "        pub fn {}_is_false() -> Filter {{\n",
                    fn_prefix
                ));
                out.push_str(&format!(
                    "            Filter::eq(\"{}\", false)\n",
                    field_name
                ));
                out.push_str("        }\n\n");
            }
        }
    }

    out.push_str("    }\n\n");
}

fn gen_order_helpers(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("    pub mod order {\n");
    out.push_str("        use super::*;\n\n");

    for f in &m.fields {
        if is_relation_object(f) {
            continue;
        }

        // Skip collection types -- can't ORDER BY a list
        if is_collection_type(&f.type_expr, schema) {
            continue;
        }

        let fn_name = to_snake(&f.name);
        let field_name = &f.name;

        out.push_str(&format!(
            "        pub fn {}_asc() -> (&'static str, Order) {{\n",
            fn_name
        ));
        out.push_str(&format!("            (\"{}\", Order::Asc)\n", field_name));
        out.push_str("        }\n\n");

        out.push_str(&format!(
            "        pub fn {}_desc() -> (&'static str, Order) {{\n",
            fn_name
        ));
        out.push_str(&format!("            (\"{}\", Order::Desc)\n", field_name));
        out.push_str("        }\n\n");
    }

    out.push_str("    }\n\n");
}

fn gen_relation_defs(out: &mut String, m: &ModelDef, schema: &Schema) {
    let relations: Vec<&FieldDef> = m.fields.iter().filter(|f| is_relation_object(f)).collect();
    if relations.is_empty() {
        return;
    }

    out.push_str("    pub mod relations {\n");
    out.push_str("        use super::*;\n\n");

    for f in &relations {
        let fn_name = to_snake(&f.name);
        let (fields, references) = get_relation_fields(f);
        let is_list = is_list_relation(f);
        let target_model = get_relation_target(f);

        let relation_type = if is_list {
            "RelationType::OneToMany"
        } else {
            // Check if target has a list relation back to us
            let target = schema.models.iter().find(|mm| mm.name == target_model);
            let has_back_list = target.is_some_and(|t| {
                t.fields.iter().any(|tf| {
                    is_relation_object(tf)
                        && is_list_relation(tf)
                        && get_relation_target(tf) == m.name
                })
            });
            if has_back_list {
                "RelationType::ManyToOne"
            } else {
                "RelationType::OneToOne"
            }
        };

        out.push_str(&format!("        pub fn {}() -> RelationDef {{\n", fn_name));
        out.push_str("            RelationDef {\n");
        out.push_str(&format!(
            "                name: \"{}\".to_string(),\n",
            f.name
        ));
        out.push_str(&format!(
            "                from_model: \"{}\".to_string(),\n",
            m.name
        ));
        out.push_str(&format!(
            "                to_model: \"{}\".to_string(),\n",
            target_model
        ));
        out.push_str(&format!(
            "                fields: vec![{}],\n",
            fields
                .iter()
                .map(|f| format!("\"{}\".to_string()", f))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        out.push_str(&format!(
            "                references: vec![{}],\n",
            references
                .iter()
                .map(|r| format!("\"{}\".to_string()", r))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        out.push_str(&format!(
            "                relation_type: {},\n",
            relation_type
        ));
        out.push_str("            }\n");
        out.push_str("        }\n\n");

        // Include helper
        out.push_str(&format!(
            "        pub fn include_{}() -> Include {{\n",
            fn_name
        ));
        out.push_str(&format!("            Include::new({}())\n", fn_name));
        out.push_str("        }\n\n");
    }

    out.push_str("    }\n\n");
}

fn gen_create_data(out: &mut String, m: &ModelDef, schema: &Schema) {
    let table_name = get_table_name(m);

    out.push_str("    #[derive(Debug, Clone)]\n");
    out.push_str("    pub struct CreateData {\n");
    for f in &m.fields {
        if is_auto_field(f) || is_relation_object(f) {
            continue;
        }
        let rust_type = type_to_value_input(&f.type_expr, schema);
        if has_default(f) || f.type_expr.nullable {
            out.push_str(&format!(
                "        pub {}: Option<{}>,\n",
                to_snake(&f.name),
                rust_type
            ));
        } else {
            out.push_str(&format!(
                "        pub {}: {},\n",
                to_snake(&f.name),
                rust_type
            ));
        }
    }
    out.push_str("    }\n\n");

    // impl to_query
    out.push_str("    impl CreateData {\n");
    out.push_str("        pub fn to_query(&self) -> BuiltQuery {\n");
    out.push_str(&format!(
        "            let mut builder = Query::table(\"{}\").create();\n",
        table_name
    ));
    for f in &m.fields {
        if is_auto_field(f) || is_relation_object(f) {
            continue;
        }
        let field_snake = to_snake(&f.name);
        let field_name = &f.name;
        if has_default(f) || f.type_expr.nullable {
            out.push_str(&format!(
                "            if let Some(ref v) = self.{} {{\n",
                field_snake
            ));
            out.push_str(&format!(
                "                builder = builder.set(\"{}\", v.clone());\n",
                field_name
            ));
            out.push_str("            }\n");
        } else {
            out.push_str(&format!(
                "            builder = builder.set(\"{}\", self.{}.clone());\n",
                field_name, field_snake
            ));
        }
    }
    out.push_str("            builder.build()\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
}

fn gen_update_data(out: &mut String, m: &ModelDef, schema: &Schema) {
    let table_name = get_table_name(m);

    out.push_str("    #[derive(Debug, Clone, Default)]\n");
    out.push_str("    pub struct UpdateData {\n");
    for f in &m.fields {
        if is_auto_field(f) || is_relation_object(f) {
            continue;
        }
        let rust_type = type_to_value_input(&f.type_expr, schema);
        out.push_str(&format!(
            "        pub {}: Option<{}>,\n",
            to_snake(&f.name),
            rust_type
        ));
    }
    out.push_str("    }\n\n");

    // impl to_query
    out.push_str("    impl UpdateData {\n");
    out.push_str("        pub fn to_query(&self, filter: Filter) -> BuiltQuery {\n");
    out.push_str(&format!(
        "            let mut builder = Query::table(\"{}\").update().filter(filter);\n",
        table_name
    ));
    for f in &m.fields {
        if is_auto_field(f) || is_relation_object(f) {
            continue;
        }
        let field_snake = to_snake(&f.name);
        let field_name = &f.name;
        out.push_str(&format!(
            "            if let Some(ref v) = self.{} {{\n",
            field_snake
        ));
        out.push_str(&format!(
            "                builder = builder.set(\"{}\", v.clone());\n",
            field_name
        ));
        out.push_str("            }\n");
    }
    out.push_str("            builder.build()\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

enum FilterType {
    Numeric,
    String,
    Boolean,
}

fn classify_filter_type(type_expr: &TypeExpr, schema: &Schema) -> FilterType {
    match &type_expr.base {
        BaseType::Boolean => FilterType::Boolean,
        BaseType::Utf8 | BaseType::LargeUtf8 => FilterType::String,
        BaseType::Named(name) => {
            if schema.enums.iter().any(|e| e.name == *name) {
                FilterType::String // enums stored as text
            } else {
                FilterType::Numeric // FK reference
            }
        }
        BaseType::Decimal128 { .. } | BaseType::Decimal256 { .. } => FilterType::String, // stored as text
        _ => FilterType::Numeric,
    }
}

fn is_collection_type(type_expr: &TypeExpr, _schema: &Schema) -> bool {
    matches!(
        type_expr.base,
        BaseType::List(_) | BaseType::LargeList(_) | BaseType::Map { .. } | BaseType::Struct(_)
    )
}

fn type_to_value_input(type_expr: &TypeExpr, schema: &Schema) -> String {
    // For CreateData/UpdateData, we use Value since that's what the query builder accepts
    match &type_expr.base {
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 | BaseType::Int64 => "i64".into(),
        BaseType::UInt8 | BaseType::UInt16 | BaseType::UInt32 | BaseType::UInt64 => "u64".into(),
        BaseType::Float16 | BaseType::Float32 | BaseType::Float64 => "f64".into(),
        BaseType::Boolean => "bool".into(),
        BaseType::Utf8
        | BaseType::LargeUtf8
        | BaseType::Decimal128 { .. }
        | BaseType::Decimal256 { .. }
        | BaseType::Date32
        | BaseType::Date64
        | BaseType::Time32 { .. }
        | BaseType::Time64 { .. }
        | BaseType::Timestamp { .. } => "String".into(),
        BaseType::Binary | BaseType::LargeBinary | BaseType::FixedSizeBinary { .. } => {
            "Vec<u8>".into()
        }
        BaseType::Named(name) => {
            if schema.enums.iter().any(|e| e.name == *name) {
                "String".into()
            } else {
                "i64".into() // FK
            }
        }
        BaseType::List(_) | BaseType::LargeList(_) | BaseType::Map { .. } | BaseType::Struct(_) => {
            "String".into()
        } // JSON serialized
    }
}

fn to_snake(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    result
}

fn to_screaming_snake(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_uppercase().next().unwrap_or(ch));
    }
    result
}

fn get_table_name(m: &ModelDef) -> String {
    for attr in &m.attributes {
        if let ModelAttribute::Map(name) = attr {
            return name.clone();
        }
    }
    m.name.clone()
}

fn is_auto_field(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Autoincrement | FieldAttribute::Id))
}

fn is_relation_object(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Relation { .. }))
}

fn has_default(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Default(_)))
}

fn get_relation_fields(f: &FieldDef) -> (Vec<String>, Vec<String>) {
    for attr in &f.attributes {
        if let FieldAttribute::Relation {
            fields, references, ..
        } = attr
        {
            return (fields.clone(), references.clone());
        }
    }
    (vec![], vec![])
}

fn get_relation_target(f: &FieldDef) -> String {
    match &f.type_expr.base {
        BaseType::Named(name) => name.clone(),
        BaseType::List(inner) | BaseType::LargeList(inner) => match &inner.base {
            BaseType::Named(name) => name.clone(),
            _ => String::new(),
        },
        _ => String::new(),
    }
}

fn is_list_relation(f: &FieldDef) -> bool {
    matches!(
        &f.type_expr.base,
        BaseType::List(_) | BaseType::LargeList(_)
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use quiver_schema::parse;

    #[test]
    fn generates_field_constants() {
        let schema = parse(
            r#"
            model User {
                id    Int32  @id @autoincrement
                email Utf8   @unique
                name  Utf8?
                score Int32  @default(0)
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub mod user {"));
        assert!(code.contains("pub const ID: &str = \"id\";"));
        assert!(code.contains("pub const EMAIL: &str = \"email\";"));
        assert!(code.contains("pub const NAME: &str = \"name\";"));
        assert!(code.contains("pub const SCORE: &str = \"score\";"));
    }

    #[test]
    fn generates_query_entry_points() {
        let schema = parse(
            r#"
            model Post {
                id    Int32 @id @autoincrement
                title Utf8
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub fn find_many() -> FindManyBuilder"));
        assert!(code.contains("pub fn find_first() -> FindFirstBuilder"));
        assert!(code.contains("pub fn create() -> CreateBuilder"));
        assert!(code.contains("pub fn create_many() -> CreateManyBuilder"));
        assert!(code.contains("pub fn update() -> UpdateBuilder"));
        assert!(code.contains("pub fn delete() -> DeleteBuilder"));
        assert!(code.contains("pub fn aggregate() -> AggregateBuilder"));
        assert!(code.contains("Query::table(\"Post\")"));
    }

    #[test]
    fn generates_filter_helpers() {
        let schema = parse(
            r#"
            model User {
                id    Int32 @id @autoincrement
                email Utf8  @unique
                score Int32
                active Boolean
                bio   Utf8?
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();

        // String field: eq, neq, in, like, contains, starts_with
        assert!(code.contains("pub fn email_eq("));
        assert!(code.contains("pub fn email_neq("));
        assert!(code.contains("pub fn email_in("));
        assert!(code.contains("pub fn email_like("));
        assert!(code.contains("pub fn email_contains("));
        assert!(code.contains("pub fn email_starts_with("));

        // Numeric field: eq, neq, gt, gte, lt, lte, between
        assert!(code.contains("pub fn score_eq("));
        assert!(code.contains("pub fn score_gt("));
        assert!(code.contains("pub fn score_between("));

        // Boolean field: is_true, is_false
        assert!(code.contains("pub fn active_is_true("));
        assert!(code.contains("pub fn active_is_false("));

        // Nullable field: is_null, is_not_null
        assert!(code.contains("pub fn bio_is_null("));
        assert!(code.contains("pub fn bio_is_not_null("));
    }

    #[test]
    fn generates_order_helpers() {
        let schema = parse(
            r#"
            model User {
                id    Int32 @id @autoincrement
                email Utf8
                score Int32
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub fn id_asc() -> (&'static str, Order)"));
        assert!(code.contains("pub fn email_desc() -> (&'static str, Order)"));
        assert!(code.contains("(\"id\", Order::Asc)"));
    }

    #[test]
    fn generates_relation_defs() {
        let schema = parse(
            r#"
            model User {
                id    Int32  @id @autoincrement
                posts Post[] @relation
            }
            model Post {
                id       Int32 @id @autoincrement
                authorId Int32
                author   User  @relation(fields: [authorId], references: [id])
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();

        // User module should have posts relation
        assert!(code.contains("pub fn posts() -> RelationDef"));
        assert!(code.contains("pub fn include_posts() -> Include"));

        // Post module should have author relation
        assert!(code.contains("pub fn author() -> RelationDef"));
        assert!(code.contains("pub fn include_author() -> Include"));
    }

    #[test]
    fn generates_create_data() {
        let schema = parse(
            r#"
            model User {
                id    Int32  @id @autoincrement
                email Utf8
                name  Utf8?
                score Int32  @default(0)
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct CreateData {"));
        // email is required
        assert!(code.contains("pub email: String,"));
        // name is nullable -> Option
        assert!(code.contains("pub name: Option<String>,"));
        // score has default -> Option
        assert!(code.contains("pub score: Option<i64>,"));
        // to_query method
        assert!(code.contains("pub fn to_query(&self) -> BuiltQuery"));
    }

    #[test]
    fn generates_update_data() {
        let schema = parse(
            r#"
            model User {
                id    Int32  @id @autoincrement
                email Utf8
                score Int32
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct UpdateData {"));
        assert!(code.contains("pub email: Option<String>,"));
        assert!(code.contains("pub score: Option<i64>,"));
        assert!(code.contains("pub fn to_query(&self, filter: Filter) -> BuiltQuery"));
    }

    #[test]
    fn table_name_uses_map_attribute() {
        let schema = parse(
            r#"
            model UserProfile {
                id Int32 @id
                @@map("user_profiles")
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub mod user_profile {"));
        assert!(code.contains("Query::table(\"user_profiles\")"));
    }

    #[test]
    fn enum_fields_get_string_filters() {
        let schema = parse(
            r#"
            enum Role { User Admin }
            model Account {
                id   Int32 @id
                role Role
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        // Enum fields should get string-like filters (like, contains)
        assert!(code.contains("pub fn role_like("));
        assert!(code.contains("pub fn role_contains("));
    }
}
