use codegen_core::CodeWriter;
use quiver_error::QuiverError;
use quiver_schema::Schema;
use quiver_schema::ast::*;

use crate::helpers::{
    has_default, is_auto_field, is_collection_base_type, to_screaming_snake, to_snake,
};

/// Generates a type-safe Rust client from a Quiver schema.
///
/// For each model, generates a module with:
/// - Field name constants (`&'static str`)
/// - Query entry points (`find_many()`, `create()`, etc.)
/// - Per-field filter constructors
/// - Relation definitions for eager loading
/// - Typed `CreateData`/`UpdateData` structs
pub struct RustClientGenerator;

impl RustClientGenerator {
    pub fn generate(schema: &Schema) -> Result<String, QuiverError> {
        let mut w = CodeWriter::new();

        w.line("// Generated by quiver-codegen. Do not edit.");
        w.blank();
        w.line("use quiver_driver_core::Value;");
        w.line("use quiver_query::{Query, BuiltQuery, Filter, Order};");
        w.line("use quiver_query::{FindManyBuilder, FindFirstBuilder, CreateBuilder};");
        w.line("use quiver_query::{CreateManyBuilder, UpdateBuilder, DeleteBuilder, UpsertBuilder};");
        w.line("use quiver_query::{AggregateBuilder, RelationDef, RelationType, Include};");
        w.blank();

        for m in &schema.models {
            gen_model_module(&mut w, m, schema);
        }

        Ok(w.finish())
    }
}

fn gen_model_module(w: &mut CodeWriter, m: &ModelDef, schema: &Schema) {
    let mod_name = to_snake(&m.name);
    let table_name = m.table_name().to_string();

    w.block(&format!("pub mod {mod_name}"), |w| {
        w.line("use super::*;");
        w.blank();

        gen_field_constants(w, m);
        gen_query_entry_points(w, &table_name);
        gen_filter_helpers(w, m, schema);
        gen_order_helpers(w, m);
        gen_relation_defs(w, m, schema);
        gen_create_data(w, m, schema);
        gen_update_data(w, m, schema);
    });
    w.blank();
}

fn gen_field_constants(w: &mut CodeWriter, m: &ModelDef) {
    w.block("pub mod fields", |w| {
        for f in &m.fields {
            let const_name = to_screaming_snake(&f.name);
            w.line(&format!("pub const {const_name}: &str = \"{name}\";", name = f.name));
        }
    });
    w.blank();
}

fn gen_query_entry_points(w: &mut CodeWriter, table_name: &str) {
    // find_many
    w.block(
        &format!("pub fn find_many() -> FindManyBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").find_many()"));
        },
    );
    w.blank();

    // find_first
    w.block(
        &format!("pub fn find_first() -> FindFirstBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").find_first()"));
        },
    );
    w.blank();

    // create
    w.block(
        &format!("pub fn create() -> CreateBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").create()"));
        },
    );
    w.blank();

    // create_many
    w.block(
        &format!("pub fn create_many() -> CreateManyBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").create_many()"));
        },
    );
    w.blank();

    // update
    w.block(
        &format!("pub fn update() -> UpdateBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").update()"));
        },
    );
    w.blank();

    // update_many
    w.block(
        &format!("pub fn update_many() -> UpdateBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").update_many()"));
        },
    );
    w.blank();

    // delete
    w.block(
        &format!("pub fn delete() -> DeleteBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").delete()"));
        },
    );
    w.blank();

    // delete_many
    w.block(
        &format!("pub fn delete_many() -> DeleteBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").delete_many()"));
        },
    );
    w.blank();

    // aggregate
    w.block(
        &format!("pub fn aggregate() -> AggregateBuilder"),
        |w| {
            w.line(&format!("Query::table(\"{table_name}\").aggregate()"));
        },
    );
    w.blank();
}

fn gen_filter_helpers(w: &mut CodeWriter, m: &ModelDef, schema: &Schema) {
    w.block("pub mod filter", |w| {
        w.line("use super::*;");
        w.blank();

        for f in &m.fields {
            let field_name = &f.name;
            let fn_prefix = to_snake(field_name);
            let filter_type = classify_filter_type(&f.type_expr, schema);

            // eq
            w.block(
                &format!("pub fn {fn_prefix}_eq(value: impl Into<Value>) -> Filter"),
                |w| {
                    w.line(&format!("Filter::eq(\"{field_name}\", value)"));
                },
            );
            w.blank();

            // neq
            w.block(
                &format!("pub fn {fn_prefix}_neq(value: impl Into<Value>) -> Filter"),
                |w| {
                    w.line(&format!("Filter::neq(\"{field_name}\", value)"));
                },
            );
            w.blank();

            // is_null (for nullable fields)
            if f.type_expr.nullable {
                w.block(
                    &format!("pub fn {fn_prefix}_is_null() -> Filter"),
                    |w| {
                        w.line(&format!("Filter::is_null(\"{field_name}\")"));
                    },
                );
                w.blank();

                w.block(
                    &format!("pub fn {fn_prefix}_is_not_null() -> Filter"),
                    |w| {
                        w.line(&format!("Filter::is_not_null(\"{field_name}\")"));
                    },
                );
                w.blank();
            }

            // in
            w.block(
                &format!("pub fn {fn_prefix}_in(values: Vec<Value>) -> Filter"),
                |w| {
                    w.line(&format!("Filter::is_in(\"{field_name}\", values)"));
                },
            );
            w.blank();

            match filter_type {
                FilterType::Numeric => {
                    for (suffix, method) in [("gt", "gt"), ("gte", "gte"), ("lt", "lt"), ("lte", "lte")] {
                        w.block(
                            &format!("pub fn {fn_prefix}_{suffix}(value: impl Into<Value>) -> Filter"),
                            |w| {
                                w.line(&format!("Filter::{method}(\"{field_name}\", value)"));
                            },
                        );
                        w.blank();
                    }

                    // between
                    w.block(
                        &format!("pub fn {fn_prefix}_between(low: impl Into<Value>, high: impl Into<Value>) -> Filter"),
                        |w| {
                            w.line(&format!("Filter::between(\"{field_name}\", low, high)"));
                        },
                    );
                    w.blank();
                }
                FilterType::String => {
                    // like
                    w.block(
                        &format!("pub fn {fn_prefix}_like(pattern: impl Into<Value>) -> Filter"),
                        |w| {
                            w.line(&format!("Filter::like(\"{field_name}\", pattern)"));
                        },
                    );
                    w.blank();

                    // contains (convenience for %value%)
                    w.block(
                        &format!("pub fn {fn_prefix}_contains(value: &str) -> Filter"),
                        |w| {
                            w.line(&format!("Filter::like(\"{field_name}\", format!(\"%{{}}%\", value))"));
                        },
                    );
                    w.blank();

                    // starts_with
                    w.block(
                        &format!("pub fn {fn_prefix}_starts_with(value: &str) -> Filter"),
                        |w| {
                            w.line(&format!("Filter::like(\"{field_name}\", format!(\"{{}}%\", value))"));
                        },
                    );
                    w.blank();

                    // gt/gte/lt/lte for ordering comparisons
                    for (suffix, method) in [("gt", "gt"), ("gte", "gte"), ("lt", "lt"), ("lte", "lte")] {
                        w.block(
                            &format!("pub fn {fn_prefix}_{suffix}(value: impl Into<Value>) -> Filter"),
                            |w| {
                                w.line(&format!("Filter::{method}(\"{field_name}\", value)"));
                            },
                        );
                        w.blank();
                    }
                }
                FilterType::Boolean => {
                    // is_true / is_false
                    w.block(
                        &format!("pub fn {fn_prefix}_is_true() -> Filter"),
                        |w| {
                            w.line(&format!("Filter::eq(\"{field_name}\", true)"));
                        },
                    );
                    w.blank();

                    w.block(
                        &format!("pub fn {fn_prefix}_is_false() -> Filter"),
                        |w| {
                            w.line(&format!("Filter::eq(\"{field_name}\", false)"));
                        },
                    );
                    w.blank();
                }
            }
        }
    });
    w.blank();
}

fn gen_order_helpers(w: &mut CodeWriter, m: &ModelDef) {
    w.block("pub mod order", |w| {
        w.line("use super::*;");
        w.blank();

        for f in &m.fields {
            // Skip collection types -- can't ORDER BY a list
            if is_collection_type(&f.type_expr) {
                continue;
            }

            let fn_name = to_snake(&f.name);
            let field_name = &f.name;

            w.block(
                &format!("pub fn {fn_name}_asc() -> (&'static str, Order)"),
                |w| {
                    w.line(&format!("(\"{field_name}\", Order::Asc)"));
                },
            );
            w.blank();

            w.block(
                &format!("pub fn {fn_name}_desc() -> (&'static str, Order)"),
                |w| {
                    w.line(&format!("(\"{field_name}\", Order::Desc)"));
                },
            );
            w.blank();
        }
    });
    w.blank();
}

fn gen_relation_defs(w: &mut CodeWriter, m: &ModelDef, schema: &Schema) {
    // Collect relations:
    // ManyToOne: from @@fk on this model (this model holds the FK)
    // OneToMany: from @@fk on other models pointing to this model
    struct RelInfo {
        name: String,
        from_model: String,
        to_model: String,
        fields: Vec<String>,
        references: Vec<String>,
        relation_type: &'static str,
    }

    let mut rels: Vec<RelInfo> = Vec::new();

    // ManyToOne: this model has @@fk pointing to another model
    for attr in &m.attributes {
        if let ModelAttribute::ForeignKey {
            fields,
            references_model,
            references_columns,
            ..
        } = attr
        {
            let fn_name = to_snake(references_model);
            rels.push(RelInfo {
                name: fn_name,
                from_model: m.name.clone(),
                to_model: references_model.clone(),
                fields: fields.clone(),
                references: references_columns.clone(),
                relation_type: "RelationType::ManyToOne",
            });
        }
    }

    // OneToMany: other models have @@fk pointing to this model
    for other in &schema.models {
        if other.name == m.name {
            continue;
        }
        for attr in &other.attributes {
            if let ModelAttribute::ForeignKey {
                fields,
                references_model,
                references_columns,
                ..
            } = attr
            {
                if references_model == &m.name {
                    let fn_name = format!("{}s", to_snake(&other.name));
                    rels.push(RelInfo {
                        name: fn_name,
                        from_model: m.name.clone(),
                        to_model: other.name.clone(),
                        fields: references_columns.clone(),
                        references: fields.clone(),
                        relation_type: "RelationType::OneToMany",
                    });
                }
            }
        }
    }

    if rels.is_empty() {
        return;
    }

    w.block("pub mod relations", |w| {
        w.line("use super::*;");
        w.blank();

        for rel in &rels {
            w.block(
                &format!("pub fn {name}() -> RelationDef", name = rel.name),
                |w| {
                    w.block("RelationDef", |w| {
                        w.line(&format!("name: \"{name}\".to_string(),", name = rel.name));
                        w.line(&format!("from_model: \"{from_model}\".to_string(),", from_model = rel.from_model));
                        w.line(&format!("to_model: \"{to_model}\".to_string(),", to_model = rel.to_model));
                        w.line(&format!(
                            "fields: vec![{}],",
                            rel.fields
                                .iter()
                                .map(|f| format!("\"{f}\".to_string()"))
                                .collect::<Vec<_>>()
                                .join(", ")
                        ));
                        w.line(&format!(
                            "references: vec![{}],",
                            rel.references
                                .iter()
                                .map(|r| format!("\"{r}\".to_string()"))
                                .collect::<Vec<_>>()
                                .join(", ")
                        ));
                        w.line(&format!("relation_type: {},", rel.relation_type));
                    });
                },
            );
            w.blank();

            // Include helper
            w.block(
                &format!("pub fn include_{name}() -> Include", name = rel.name),
                |w| {
                    w.line(&format!("Include::new({name}())", name = rel.name));
                },
            );
            w.blank();
        }
    });
    w.blank();
}

fn gen_create_data(w: &mut CodeWriter, m: &ModelDef, schema: &Schema) {
    let table_name = m.table_name().to_string();

    w.line("#[derive(Debug, Clone)]");
    w.block("pub struct CreateData", |w| {
        for f in &m.fields {
            if is_auto_field(f) {
                continue;
            }
            let rust_type = type_to_value_input(&f.type_expr, schema);
            let field_name = to_snake(&f.name);
            if has_default(f) || f.type_expr.nullable {
                w.line(&format!("pub {field_name}: Option<{rust_type}>,"));
            } else {
                w.line(&format!("pub {field_name}: {rust_type},"));
            }
        }
    });
    w.blank();

    // impl to_query
    w.block("impl CreateData", |w| {
        w.block("pub fn to_query(&self) -> BuiltQuery", |w| {
            w.line(&format!("let mut builder = Query::table(\"{table_name}\").create();"));
            for f in &m.fields {
                if is_auto_field(f) {
                    continue;
                }
                let field_snake = to_snake(&f.name);
                let field_name = &f.name;
                if has_default(f) || f.type_expr.nullable {
                    w.block(
                        &format!("if let Some(ref v) = self.{field_snake}"),
                        |w| {
                            w.line(&format!("builder = builder.set(\"{field_name}\", v.clone());"));
                        },
                    );
                } else {
                    w.line(&format!("builder = builder.set(\"{field_name}\", self.{field_snake}.clone());"));
                }
            }
            w.line("builder.build()");
        });
    });
    w.blank();
}

fn gen_update_data(w: &mut CodeWriter, m: &ModelDef, schema: &Schema) {
    let table_name = m.table_name().to_string();

    w.line("#[derive(Debug, Clone, Default)]");
    w.block("pub struct UpdateData", |w| {
        for f in &m.fields {
            if is_auto_field(f) {
                continue;
            }
            let rust_type = type_to_value_input(&f.type_expr, schema);
            let field_name = to_snake(&f.name);
            w.line(&format!("pub {field_name}: Option<{rust_type}>,"));
        }
    });
    w.blank();

    // impl to_query
    w.block("impl UpdateData", |w| {
        w.block(
            "pub fn to_query(&self, filter: Filter) -> BuiltQuery",
            |w| {
                w.line(&format!("let mut builder = Query::table(\"{table_name}\").update().filter(filter);"));
                for f in &m.fields {
                    if is_auto_field(f) {
                        continue;
                    }
                    let field_snake = to_snake(&f.name);
                    let field_name = &f.name;
                    w.block(
                        &format!("if let Some(ref v) = self.{field_snake}"),
                        |w| {
                            w.line(&format!("builder = builder.set(\"{field_name}\", v.clone());"));
                        },
                    );
                }
                w.line("builder.build()");
            },
        );
    });
    w.blank();
}

enum FilterType {
    Numeric,
    String,
    Boolean,
}

fn classify_filter_type(type_expr: &TypeExpr, schema: &Schema) -> FilterType {
    match &type_expr.base {
        BaseType::Boolean => FilterType::Boolean,
        BaseType::Utf8 | BaseType::LargeUtf8 => FilterType::String,
        BaseType::Named(name) => {
            if schema.enums.iter().any(|e| e.name == *name) {
                FilterType::String // enums stored as text
            } else {
                FilterType::Numeric // FK reference
            }
        }
        BaseType::Decimal128 { .. } | BaseType::Decimal256 { .. } => FilterType::String, // stored as text
        _ => FilterType::Numeric,
    }
}

fn is_collection_type(type_expr: &TypeExpr) -> bool {
    is_collection_base_type(&type_expr.base) || matches!(type_expr.base, BaseType::Struct(_))
}

fn type_to_value_input(type_expr: &TypeExpr, schema: &Schema) -> String {
    // For CreateData/UpdateData, we use Value since that's what the query builder accepts
    match &type_expr.base {
        BaseType::Int8 | BaseType::Int16 | BaseType::Int32 | BaseType::Int64 => "i64".into(),
        BaseType::UInt8 | BaseType::UInt16 | BaseType::UInt32 | BaseType::UInt64 => "u64".into(),
        BaseType::Float16 | BaseType::Float32 | BaseType::Float64 => "f64".into(),
        BaseType::Boolean => "bool".into(),
        BaseType::Utf8
        | BaseType::LargeUtf8
        | BaseType::Decimal128 { .. }
        | BaseType::Decimal256 { .. }
        | BaseType::Date32
        | BaseType::Date64
        | BaseType::Time32 { .. }
        | BaseType::Time64 { .. }
        | BaseType::Timestamp { .. } => "String".into(),
        BaseType::Binary | BaseType::LargeBinary | BaseType::FixedSizeBinary { .. } => {
            "Vec<u8>".into()
        }
        BaseType::Named(name) => {
            if schema.enums.iter().any(|e| e.name == *name) {
                "String".into()
            } else {
                "i64".into() // FK
            }
        }
        BaseType::List(_) | BaseType::LargeList(_) | BaseType::Map { .. } | BaseType::Struct(_) => {
            "String".into()
        } // JSON serialized
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use quiver_schema::parse;

    #[test]
    fn generates_field_constants() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8?
                score Int32  DEFAULT 0
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub mod user {"));
        assert!(code.contains("pub const ID: &str = \"id\";"));
        assert!(code.contains("pub const EMAIL: &str = \"email\";"));
        assert!(code.contains("pub const NAME: &str = \"name\";"));
        assert!(code.contains("pub const SCORE: &str = \"score\";"));
    }

    #[test]
    fn generates_query_entry_points() {
        let schema = parse(
            r#"
            model Post {
                id    Int32 PRIMARY KEY AUTOINCREMENT
                title Utf8
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub fn find_many() -> FindManyBuilder"));
        assert!(code.contains("pub fn find_first() -> FindFirstBuilder"));
        assert!(code.contains("pub fn create() -> CreateBuilder"));
        assert!(code.contains("pub fn create_many() -> CreateManyBuilder"));
        assert!(code.contains("pub fn update() -> UpdateBuilder"));
        assert!(code.contains("pub fn delete() -> DeleteBuilder"));
        assert!(code.contains("pub fn aggregate() -> AggregateBuilder"));
        assert!(code.contains("Query::table(\"Post\")"));
    }

    #[test]
    fn generates_filter_helpers() {
        let schema = parse(
            r#"
            model User {
                id    Int32 PRIMARY KEY AUTOINCREMENT
                email Utf8  UNIQUE
                score Int32
                active Boolean
                bio   Utf8?
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();

        // String field: eq, neq, in, like, contains, starts_with
        assert!(code.contains("pub fn email_eq("));
        assert!(code.contains("pub fn email_neq("));
        assert!(code.contains("pub fn email_in("));
        assert!(code.contains("pub fn email_like("));
        assert!(code.contains("pub fn email_contains("));
        assert!(code.contains("pub fn email_starts_with("));

        // Numeric field: eq, neq, gt, gte, lt, lte, between
        assert!(code.contains("pub fn score_eq("));
        assert!(code.contains("pub fn score_gt("));
        assert!(code.contains("pub fn score_between("));

        // Boolean field: is_true, is_false
        assert!(code.contains("pub fn active_is_true("));
        assert!(code.contains("pub fn active_is_false("));

        // Nullable field: is_null, is_not_null
        assert!(code.contains("pub fn bio_is_null("));
        assert!(code.contains("pub fn bio_is_not_null("));
    }

    #[test]
    fn generates_order_helpers() {
        let schema = parse(
            r#"
            model User {
                id    Int32 PRIMARY KEY AUTOINCREMENT
                email Utf8
                score Int32
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub fn id_asc() -> (&'static str, Order)"));
        assert!(code.contains("pub fn email_desc() -> (&'static str, Order)"));
        assert!(code.contains("(\"id\", Order::Asc)"));
    }

    #[test]
    fn generates_relation_defs() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
            }
            model Post {
                id       Int32 PRIMARY KEY AUTOINCREMENT
                authorId Int32
                FOREIGN KEY (authorId) REFERENCES User (id)
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();

        // User module should have posts relation (OneToMany: other model "Post" -> "posts")
        assert!(code.contains("pub fn posts() -> RelationDef"));
        assert!(code.contains("pub fn include_posts() -> Include"));

        // Post module should have user relation (ManyToOne: FK references "User" -> "user")
        assert!(code.contains("pub fn user() -> RelationDef"));
        assert!(code.contains("pub fn include_user() -> Include"));
    }

    #[test]
    fn generates_create_data() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8
                name  Utf8?
                score Int32  DEFAULT 0
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct CreateData {"));
        // email is required
        assert!(code.contains("pub email: String,"));
        // name is nullable -> Option
        assert!(code.contains("pub name: Option<String>,"));
        // score has default -> Option
        assert!(code.contains("pub score: Option<i64>,"));
        // to_query method
        assert!(code.contains("pub fn to_query(&self) -> BuiltQuery"));
    }

    #[test]
    fn generates_update_data() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8
                score Int32
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct UpdateData {"));
        assert!(code.contains("pub email: Option<String>,"));
        assert!(code.contains("pub score: Option<i64>,"));
        assert!(code.contains("pub fn to_query(&self, filter: Filter) -> BuiltQuery"));
    }

    #[test]
    fn table_name_uses_map_attribute() {
        let schema = parse(
            r#"
            model UserProfile {
                id Int32 PRIMARY KEY
                MAP "user_profiles"
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub mod user_profile {"));
        assert!(code.contains("Query::table(\"user_profiles\")"));
    }

    #[test]
    fn enum_fields_get_string_filters() {
        let schema = parse(
            r#"
            enum Role { User Admin }
            model Account {
                id   Int32 PRIMARY KEY
                role Role
            }
        "#,
        )
        .unwrap();
        let code = RustClientGenerator::generate(&schema).unwrap();
        // Enum fields should get string-like filters (like, contains)
        assert!(code.contains("pub fn role_like("));
        assert!(code.contains("pub fn role_contains("));
    }
}
