use quiver_error::QuiverError;
use quiver_schema::Schema;
use quiver_schema::ast::*;

/// Generates native Rust structs with serde derives from a Quiver schema.
///
/// Unlike the FBS/Proto backends, this generates idiomatic Rust types directly
/// without an intermediate schema format.
pub struct RustSerdeGenerator;

impl RustSerdeGenerator {
    pub fn generate(schema: &Schema) -> Result<String, QuiverError> {
        let mut out = String::new();

        out.push_str("// Generated by quiver-codegen. Do not edit.\n\n");
        out.push_str("use serde::{Serialize, Deserialize};\n\n");

        for e in &schema.enums {
            gen_enum(&mut out, e);
        }

        for m in &schema.models {
            gen_struct(&mut out, m, schema);
            gen_create_input(&mut out, m, schema);
            gen_update_input(&mut out, m, schema);
        }

        Ok(out)
    }
}

fn gen_enum(out: &mut String, e: &EnumDef) {
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub enum {} {{\n", e.name));
    for v in &e.values {
        out.push_str(&format!("    {},\n", v.name));
    }
    out.push_str("}\n\n");
}

fn gen_struct(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");

    // Add serde rename_all if @@map is present (indicates non-Rust naming)
    if get_map_name(&m.attributes).is_some() {
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
    }

    out.push_str(&format!("pub struct {} {{\n", m.name));
    for f in &m.fields {
        let rust_type = type_to_rust(&f.type_expr, schema);
        let col_rename = get_field_map_name(f);
        if let Some(rename) = col_rename {
            out.push_str(&format!("    #[serde(rename = \"{}\")]\n", rename));
        }
        out.push_str(&format!("    pub {}: {},\n", to_snake(&f.name), rust_type));
    }
    out.push_str("}\n\n");
}

fn gen_create_input(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {}CreateInput {{\n", m.name));
    for f in &m.fields {
        if is_auto_field(f) {
            continue;
        }
        let base_type = type_to_rust(&f.type_expr, schema);
        // Fields with defaults or nullable become Option in create input
        if has_default(f) && !f.type_expr.nullable {
            out.push_str(&format!(
                "    pub {}: Option<{}>,\n",
                to_snake(&f.name),
                base_rust_type(&f.type_expr.base, schema)
            ));
        } else {
            out.push_str(&format!("    pub {}: {},\n", to_snake(&f.name), base_type));
        }
    }
    out.push_str("}\n\n");
}

fn gen_update_input(out: &mut String, m: &ModelDef, schema: &Schema) {
    out.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {}UpdateInput {{\n", m.name));
    for f in &m.fields {
        if is_auto_field(f) {
            continue;
        }
        let base = base_rust_type(&f.type_expr.base, schema);
        // All fields optional in update
        out.push_str(&format!(
            "    pub {}: Option<{}>,\n",
            to_snake(&f.name),
            base
        ));
    }
    out.push_str("}\n\n");
}

fn type_to_rust(type_expr: &TypeExpr, schema: &Schema) -> String {
    let base = base_rust_type(&type_expr.base, schema);
    if type_expr.nullable {
        format!("Option<{}>", base)
    } else {
        base
    }
}

fn base_rust_type(base: &BaseType, schema: &Schema) -> String {
    match base {
        BaseType::Int8 => "i8".into(),
        BaseType::Int16 => "i16".into(),
        BaseType::Int32 => "i32".into(),
        BaseType::Int64 => "i64".into(),
        BaseType::UInt8 => "u8".into(),
        BaseType::UInt16 => "u16".into(),
        BaseType::UInt32 => "u32".into(),
        BaseType::UInt64 => "u64".into(),
        BaseType::Float16 => "f32".into(),
        BaseType::Float32 => "f32".into(),
        BaseType::Float64 => "f64".into(),
        BaseType::Decimal128 { .. } | BaseType::Decimal256 { .. } => "String".into(),
        BaseType::Utf8 | BaseType::LargeUtf8 => "String".into(),
        BaseType::Binary | BaseType::LargeBinary | BaseType::FixedSizeBinary { .. } => {
            "Vec<u8>".into()
        }
        BaseType::Boolean => "bool".into(),
        BaseType::Date32 | BaseType::Date64 => "String".into(),
        BaseType::Time32 { .. } | BaseType::Time64 { .. } => "String".into(),
        BaseType::Timestamp { .. } => "String".into(),
        BaseType::List(inner) | BaseType::LargeList(inner) => {
            format!("Vec<{}>", base_rust_type(&inner.base, schema))
        }
        BaseType::Map { key, value } => {
            format!(
                "std::collections::HashMap<{}, {}>",
                base_rust_type(&key.base, schema),
                base_rust_type(&value.base, schema)
            )
        }
        BaseType::Struct(_) => "serde_json::Value".into(),
        BaseType::Named(name) => {
            if schema.enums.iter().any(|e| e.name == *name) {
                name.clone()
            } else {
                // FK reference -- use the PK type (assume i32 for now)
                "i32".into()
            }
        }
    }
}

fn to_snake(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    result
}

fn is_auto_field(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Autoincrement | FieldAttribute::Id))
}

fn has_default(f: &FieldDef) -> bool {
    f.attributes
        .iter()
        .any(|a| matches!(a, FieldAttribute::Default(_)))
}

fn get_map_name(attrs: &[ModelAttribute]) -> Option<&str> {
    for attr in attrs {
        if let ModelAttribute::Map(name) = attr {
            return Some(name);
        }
    }
    None
}

fn get_field_map_name(f: &FieldDef) -> Option<&str> {
    for attr in &f.attributes {
        if let FieldAttribute::Map(name) = attr {
            return Some(name);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use quiver_schema::parse;

    #[test]
    fn generate_simple_struct() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8   UNIQUE
                name  Utf8?
                age   Int16
                active Boolean DEFAULT true
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct User {"));
        assert!(code.contains("pub email: String,"));
        assert!(code.contains("pub name: Option<String>,"));
        assert!(code.contains("pub age: i16,"));
        assert!(code.contains("pub active: bool,"));
        // id excluded from struct? No -- id is in the main struct, just excluded from CreateInput
        assert!(code.contains("pub id: i32,"));
    }

    #[test]
    fn generate_enum_and_reference() {
        let schema = parse(
            r#"
            enum Role { User Admin Moderator }
            model Account {
                id   Int32 PRIMARY KEY
                role Role
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub enum Role {"));
        assert!(code.contains("    User,"));
        assert!(code.contains("    Admin,"));
        assert!(code.contains("    Moderator,"));
        assert!(code.contains("pub role: Role,"));
    }

    #[test]
    fn generate_create_input_excludes_auto() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY AUTOINCREMENT
                email Utf8
                name  Utf8?
                active Boolean DEFAULT true
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct UserCreateInput {"));
        // id should be excluded (autoincrement + @id)
        let create_block = code.split("pub struct UserCreateInput").nth(1).unwrap();
        let create_block = create_block.split('}').next().unwrap();
        assert!(!create_block.contains("id:"));
        // email required
        assert!(create_block.contains("pub email: String,"));
        // name is nullable -> Option
        assert!(create_block.contains("pub name: Option<String>,"));
        // active has default -> Option in create
        assert!(create_block.contains("pub active: Option<bool>,"));
    }

    #[test]
    fn generate_update_input_all_optional() {
        let schema = parse(
            r#"
            model User {
                id    Int32 PRIMARY KEY AUTOINCREMENT
                email Utf8
                score Int32
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub struct UserUpdateInput {"));
        let update_block = code.split("pub struct UserUpdateInput").nth(1).unwrap();
        let update_block = update_block.split('}').next().unwrap();
        assert!(update_block.contains("pub email: Option<String>,"));
        assert!(update_block.contains("pub score: Option<i32>,"));
        assert!(!update_block.contains("id:"));
    }

    #[test]
    fn generate_list_and_map_types() {
        let schema = parse(
            r#"
            model Doc {
                id    Int32 PRIMARY KEY
                tags  List<Utf8>
                meta  Map<Utf8, Int32>
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub tags: Vec<String>,"));
        assert!(code.contains("pub meta: std::collections::HashMap<String, i32>,"));
    }

    #[test]
    fn generate_temporal_types() {
        let schema = parse(
            r#"
            model Event {
                id      Int32 PRIMARY KEY
                created Timestamp(Microsecond, UTC)
                day     Date32
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("pub created: String,"));
        assert!(code.contains("pub day: String,"));
    }

    #[test]
    fn generate_field_rename() {
        let schema = parse(
            r#"
            model UserProfile {
                id       Int32 PRIMARY KEY
                fullName Utf8  MAP "full_name"
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("#[serde(rename = \"full_name\")]"));
        assert!(code.contains("pub full_name: String,"));
    }

    #[test]
    fn generate_relation_excluded() {
        let schema = parse(
            r#"
            model User {
                id    Int32  PRIMARY KEY
            }
            model Post {
                id       Int32 PRIMARY KEY
                authorId Int32
                FOREIGN KEY (authorId) REFERENCES User (id)
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        let user_block = code.split("pub struct User {").nth(1).unwrap();
        let user_block = user_block.split('}').next().unwrap();
        assert!(!user_block.contains("posts"));

        let post_block = code.split("pub struct Post {").nth(1).unwrap();
        let post_block = post_block.split('}').next().unwrap();
        // "author" relation object should be excluded, but "author_id" FK kept
        assert!(!post_block.contains("pub author:"));
        assert!(post_block.contains("pub author_id: i32,"));
    }

    #[test]
    fn derive_default_on_update_input() {
        let schema = parse(
            r#"
            model Item {
                id   Int32 PRIMARY KEY AUTOINCREMENT
                name Utf8
            }
        "#,
        )
        .unwrap();
        let code = RustSerdeGenerator::generate(&schema).unwrap();
        assert!(code.contains("#[derive(Debug, Clone, Default, Serialize, Deserialize)]"));
    }
}
